[info]
        relay_url = "ws://rothbard.lab.networks.deavmi.assigned.network:1488"
        name = "King of Lesotho"
        description = "Deavmi's personal relay (also the king is a pretender)"
        pubkey = "d6149823c90c4865e4bc434a4be1a1ee8f72aabd8328dd059ba4f11f7633b0b6"
        contact = "mailto:deavmi@redxen.eu"

[database]
        engine = "postgres"
        min_conn = 0
        max_conn = 4
        connection = "postgresql://dbuser:dbpass@[::]:5432/nostr"

[authorization]
       	# Only allow myself to publish events
        pubkey_whitelist = [
                "d6149823c90c4865e4bc434a4be1a1ee8f72aabd8328dd059ba4f11f7633b0b6"
        ]

[network]
        address = "[::]"
        port = 7000
        remote_ip_header = "x-forwarded-for"

[verified_users]
        # TODO: Figure this out, didn't work for me OR others
        mode = "passive"

        # Check verification every 2 days
        verify_expiration = "2 days"

        # When attempting verification, retry every
        verify_update_frequency = "30 minutes"

        # Give up retrying after this many tries
        max_consecutive_failures = 6
